services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - SERVER_REGIONS=${VPN_REGIONS}
      - VPN_PORT_FORWARDING=${VPN_PORT_FORWARDING}
      - VPN_PORT_FORWARDING_PROVIDER=${VPN_PORT_FORWARDING_PROVIDER}
      - VPN_PORT_FORWARDING_STATUS_FILE=/gluetun/forwarded_port
      - FIREWALL_OUTBOUND_SUBNETS=${LAN_NETWORK}
      - HTTPPROXY=off
      - SHADOWSOCKS=off
    volumes:
      - ${APP_ROOT}/data/gluetun:/gluetun
    ports:
      - ${QBIT_WEBUI_PORT}:${QBIT_WEBUI_PORT}
      - ${QBIT_TORRENT_PORT}:${QBIT_TORRENT_PORT}
      - ${QBIT_TORRENT_PORT}:${QBIT_TORRENT_PORT}/udp
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${QBIT_WEBUI_PORT}
      - TORRENTING_PORT=${QBIT_TORRENT_PORT}
    volumes:
      - ${APP_ROOT}/data/qbittorrent:/config
      - ${DATA_ROOT}:/data
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APP_ROOT}/data/prowlarr:/config
    ports:
      - ${PROWLARR_PORT}:9696
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APP_ROOT}/data/sonarr:/config
      - ${DATA_ROOT}:/data
    ports:
      - ${SONARR_PORT}:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APP_ROOT}/data/radarr:/config
      - ${DATA_ROOT}:/data
    ports:
      - ${RADARR_PORT}:7878
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APP_ROOT}/data/lidarr:/config
      - ${DATA_ROOT}:/data
    ports:
      - ${LIDARR_PORT}:8686
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APP_ROOT}/data/filebrowser:/config
      - ${APP_ROOT}:/stack
      - ${DATA_ROOT}:/data
    ports:
      - ${FILEBROWSER_PORT}:80
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    profiles:
      - sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APP_ROOT}/data/sabnzbd:/config
      - ${DATA_ROOT}:/data
    ports:
      - ${SABNZBD_PORT}:8080
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    profiles:
      - bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APP_ROOT}/data/bazarr:/config
      - ${DATA_ROOT}:/data
    ports:
      - ${BAZARR_PORT}:6767
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    profiles:
      - readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APP_ROOT}/data/readarr:/config
      - ${DATA_ROOT}:/data
    ports:
      - ${READARR_PORT}:8787
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    profiles:
      - flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
    ports:
      - 8191:8191
    restart: unless-stopped

  unpackerr:
    image: golift/unpackerr:latest
    container_name: unpackerr
    profiles:
      - unpackerr
    environment:
      - TZ=${TZ}
      - UN_LOG_FILE=/logs/unpackerr.log
    volumes:
      - ${APP_ROOT}/data/unpackerr:/config
      - ${APP_ROOT}/logs:/logs
      - ${DATA_ROOT}:/data
    restart: unless-stopped

  dozzle-agent:
    image: amir20/dozzle:latest
    container_name: dozzle-agent
    profiles:
      - dozzle
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - ${DOZZLE_AGENT_PORT}:7007
    restart: unless-stopped
